In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(5,)

In [8]:
L1 = [1,2,3,4,5]
L2 = [6,7,8,9,10]
L3 = [3,5,2,3,4]

arr1 = np.array([L1,L2,L3])

arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 3,  5,  2,  3,  4]])

In [10]:
arr1.shape

(3, 5)

In [15]:
arr1.reshape(1,15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  3,  5,  2,  3,  4]])

# Indexing

In [16]:
arr

array([1, 2, 3, 4, 5])

In [19]:
arr[4]

5

In [20]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 3,  5,  2,  3,  4]])

In [21]:
arr1[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 3,  5,  2,  3,  4]])

In [23]:
arr1[1:,3:]

array([[ 9, 10],
       [ 3,  4]])

In [24]:
arr1[1:2,2:4]

array([[8, 9]])

In [25]:
arr1[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 3,  5,  2,  3,  4]])

# Arange

In [27]:
arr2 = np.arange(1,10)
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr2 = np.arange(1,20, 2)
arr2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# Linspace

used to print the random number between specific range [just like lorem ipsum in web dev]

In [35]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

## Broadcasting

In [36]:
arr2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [40]:
arr2[3:] = 100
arr2

array([  1,   3,   5, 100, 100, 100, 100, 100, 100, 100])

In [41]:
arr3 = arr2

In [44]:
arr3[3:] = 500
arr3

array([  1,   3,   5, 500, 500, 500, 500, 500, 500, 500])

In [45]:
arr2

array([  1,   3,   5, 500, 500, 500, 500, 500, 500, 500])

## Copy