In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(5,)

In [6]:
L1 = [1,2,3,4,5]
L2 = [6,7,8,9,10]
L3 = [3,5,2,3,4]

arr1 = np.array([L1,L2,L3])

arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 3,  5,  2,  3,  4]])

In [7]:
arr1.shape

(3, 5)

In [8]:
arr1.reshape(1,15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  3,  5,  2,  3,  4]])

# Indexing

In [9]:
arr

array([1, 2, 3, 4, 5])

In [10]:
arr[4]

5

In [11]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 3,  5,  2,  3,  4]])

In [12]:
arr1[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 3,  5,  2,  3,  4]])

In [13]:
arr1[1:,3:]

array([[ 9, 10],
       [ 3,  4]])

In [14]:
arr1[1:2,2:4]

array([[8, 9]])

In [15]:
arr1[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 3,  5,  2,  3,  4]])

# Arange

In [16]:
arr2 = np.arange(1,10)
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr2 = np.arange(1,20, 2)
arr2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# Linspace

used to print the random number between specific range [just like lorem ipsum in web dev]

In [18]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

## Broadcasting

In [19]:
arr2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [20]:
arr2[3:] = 100
arr2

array([  1,   3,   5, 100, 100, 100, 100, 100, 100, 100])

In [21]:
arr3 = arr2

In [22]:
arr3[3:] = 500
arr3

array([  1,   3,   5, 500, 500, 500, 500, 500, 500, 500])

In [23]:
arr2

array([  1,   3,   5, 500, 500, 500, 500, 500, 500, 500])

## Copy

In [31]:
arr3 = arr2.copy()
arr3[3:] = 1000
arr3

array([   1,    3,    5, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [32]:
arr2

array([  1,   3,   5, 500, 500, 500, 500, 500, 500, 500])

In [33]:
arr2 == arr3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [41]:
arr3[arr3>500]

array([1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [48]:
arr2 >= arr3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [53]:
arr2 ** 2

array([     1,      9,     25, 250000, 250000, 250000, 250000, 250000,
       250000, 250000])

In [54]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [55]:
np.ones((5), dtype = int)

array([1, 1, 1, 1, 1])

In [57]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [61]:
np.random.rand(5,3)

array([[0.45678256, 0.23984545, 0.59313749],
       [0.51399536, 0.46850578, 0.69337387],
       [0.05827566, 0.132242  , 0.34554119],
       [0.79902117, 0.77294009, 0.33029163],
       [0.86292537, 0.5509556 , 0.45986222]])

In [62]:
np.random.rand((5,3), dtype = int) 
# Just to let me know that dtype is not a parameter of random

TypeError: rand() got an unexpected keyword argument 'dtype'

In [63]:
np.random.randn(3,4)

array([[ 1.17962581, -1.30170501,  1.33415282, -0.01646813],
       [-0.8388863 , -0.01475004,  0.68321537, -1.29221811],
       [ 0.73353262,  1.05685622,  0.48029775, -2.00766596]])

In [68]:
np.random.randint(1,10,6).reshape(2,3)

array([[7, 7, 9],
       [2, 4, 8]])