In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(5,)

In [8]:
L1 = [1,2,3,4,5]
L2 = [6,7,8,9,10]
L3 = [3,5,2,3,4]

arr1 = np.array([L1,L2,L3])

arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 3,  5,  2,  3,  4]])

In [10]:
arr1.shape

(3, 5)

In [13]:
arr1.reshape(1,15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  3,  5,  2,  3,  4]])